### ISSUE TITLE
Make decision to prepare for course

### ISSUE THREAD

**Issue by richelbilderbeek** [rscherrer/ExplicitGenomeSpeciation#22]
(these are just me putting my though somewhere)

Problem: code must run on all OSes

## Solution 1: all students must install Qt Creator and compile the code

 * Pro: easy for us
 * Con: Qt Creator install can take one hour, students needs to (freely) register at Qt

## Solution 2: compile to a standalone Windows executable, use Thijs' setup

Linux and Mac users must install Wine

 * Pro: works easily on Windows, can publish link to .exe on website, Thijs can do it
 * Con: unsure if this works, Raph cannot run his own GUI on his favorite OS

## Solution 3: cross-compile to a standalone Windows executable, use Qt

Linux and Mac users must install Wine

 * Pro: works easily on Windows, can publish link to .exe on website
 * Con: depend on me for cross-compile (toolchain takes tens of hours to setup), but can show Raph how easy it is

## Solution 4: make it into an R package, raw output

Students can create plots by ggplot2.

 * Pro: easy for all
 * Con: harder for us

## Solution 5: make it into an R package, use `shiny` as GUI

 * Pro: easy for all
 * Con: harder for us

**Comment by thijsjanzen** [comment]
To which extent can you compile to standalone executable for each OS, using Qt?

Shiny and R are difficult, because this would mean generating intermediate output from the c++ code - I'm unsure how to ping-pong data between c++ and R, whilst retaining the state of all elements in C++ (so you can continue the simulation). 

One way to do that is to call plotting commands from within the C++ code (using Rcpp). Con of that is that it is not very flexible.

**Comment by richelbilderbeek** [comment]
> To which extent can you compile to standalone executable for each OS, using Qt?

Qt works on each major platform, so a native compile will work.

**Comment by richelbilderbeek** [comment]
Result of meeting with Raph: option 3.

**Comment by rscherrer** [comment]
@richelbilderbeek, Thijs and I would need a bit more clarification on why it is not possible to have a standalone for Mac and a standalone for Windows, so that Mac users do not have to use Wine. I understand it has to do with performance but... is that really gonna be a problem? I propose we meet on Wednesday to chat a bit about this, if you have time. How does that sound?

**Comment by richelbilderbeek** [comment]
>  I understand it has to do with performance but... is that really gonna be a problem? 

It's not about performance, but about compatibility and ease for the users. We know/assume a Windows executable works on Wine, which we can easily supply.

We can supply a native Mac compiled program, but I (strongly) predict it won't work on all Macs.

We can let the kids compile natively on their Macs, but I predict this will be hard for the ~~n00bs~~ students.

> I propose we meet on Wednesday to chat a bit about this, if you have time. How does that sound?

Sure, after/during the TRES meeting would be fine!

**Comment by richelbilderbeek** [comment]
I guess this can be closed now :+1:
